### ISSUE TITLE
Upgrade provider 'random' to v1.3.1 or v2.1.2

### ISSUE THREAD

**Issue by sshvetsov** [traveloka/terraform-aws-resource-naming#19]
Since this module has been released, the version of the provider "random" used by this module has been [upgraded multiple times](https://github.com/terraform-providers/terraform-provider-random/blob/master/CHANGELOG.md).

The latest version of the provider "random" is v2.1.2 at the time of this writing.
I think this particular module could be safely upgrade to at least version 1.3.1, possibly even 2.1.2

One good reason to upgrade to version > 2.1.0 is support for Terraform 0.12.

**Comment by isen-ng** [comment]
See https://github.com/traveloka/terraform-aws-resource-naming/issues/20#issuecomment-495458420
